#TODO: Extracate all connection strings here
spring:
  data:
    mongodb:
      uri: "mongodb+srv://<USERNAME>:<PASSWORD>@cluster0.fnsv9.gcp.mongodb.net/?retryWrites=true&w=majority"
      database: DateApp

chatgpt:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: "<API_KEY>"
    model: "gpt-4o-mini"
    max_tokens: 5