#TODO: Extracate all connection strings here
spring:
  data:
    mongodb:
      uri: "mongodb+srv://mualvi:iloverona@cluster0.fnsv9.gcp.mongodb.net/?retryWrites=true&w=majority"
      database: DateApp
